Fix docs: Construct new TwoFactorAuth-class
RobThree/TwoFactorAuth pull request #110
Opened 2023-06-05 14:11 UTC by modelrailroader

Hey, 
your documentation to create a new object of the TwoFactorAuth class is wrong. 
A single string like "sha1" is not enough; expected is an argument of Algorithm.

2023-06-05 17:57 UTC, willpower232 requested changes
This is an excellent observation however technically one doesn't need to specify the other arguments now the minimum supported version of PHP is greater than 8 so this example could be `$tfa = new TwoFactorAuth(qrcodeprovider: $qrCodeProvider);`

That said, the documentation about algorithm at docs/optional-configuration.md is definitely out of date.

2023-06-08 14:57 UTC, modelrailroader commented
Sorry, I really forget this. 
Do you think like this? I'm not so familiar with PHP 8 and all the changes yet...

2023-06-11 09:42 UTC, willpower232 commented
In this case it makes sense as I can imagine a significant number of users would just want to specify the name of the application and a QR code provider, unless one is developing for a specific hardware token or custom application then the default SHA1 should suffice which thanks to PHP 8 means you don't need to specify most of the constructor arguments.

Are you going to edit docs/optional-configuration.md as well?

2023-06-11 10:28 UTC, modelrailroader commented
Done.

> In this case it makes sense as I can imagine a significant number of users would just want to specify the name of the application and a QR code provider

But wouldn't it then not making more sense to change the position of the CodeProvider, so that the time when a code gets unvalid and the number of digits don't have to specified when defining the class?

Like this:
`$tfa = new TwoFactorAuth(null, YourChosenProvider: $qrCodeProvider, 6, 30, Algorithm::Sha1);`

2023-06-23 15:58 UTC, modelrailroader commented
I have done this now, like you proposed. 

Additionally, I fixed the hyperlinks for the documentation about the different online and offline providers. All hyperlinks had the file extension ".html", but it is ".md". ;-)

2023-06-23 16:09 UTC, RobThree approved these changes

2023-06-23 19:14 UTC, willpower232 requested changes

2023-06-23 19:14 UTC, willpower232 commented on docs/qr-codes.md
> -
I think it is clearer if you put this back

2023-06-23 19:23 UTC, modelrailroader commented
You're right! Changed it.

2023-07-29 14:36 UTC, willpower232 approved these changes

2023-07-29 14:36 UTC, merged

2023-07-29 14:37 UTC, willpower232 commented
apologies for the delay! I wanted to do this at a time I could watch the build to make sure the docs website still works.